CREATE TABLE `waitlist_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`email` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`phone` text,
	`annual_income_range` text NOT NULL,
	`target_home_budget` text NOT NULL,
	`purchase_timeline` text NOT NULL,
	`current_housing` text NOT NULL,
	`current_monthly_payment` integer,
	`zip_code` text NOT NULL,
	`utm_source` text,
	`notes` text,
	`entertainment_amount` integer,
	`entertainment_provider` text,
	`entertainment_provider_other` text,
	`home_insurance_amount` integer,
	`home_insurance_provider` text,
	`home_insurance_provider_other` text,
	`utilities_amount` integer,
	`utilities_provider` text,
	`utilities_provider_other` text,
	`car_payment_amount` integer,
	`car_payment_provider` text,
	`car_payment_provider_other` text,
	`car_insurance_amount` integer,
	`car_insurance_provider` text,
	`car_insurance_provider_other` text,
	`internet_amount` integer,
	`internet_provider` text,
	`internet_provider_other` text,
	`phone_amount` integer,
	`phone_provider` text,
	`phone_provider_other` text,
	`created_at` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `waitlist_entries_email_unique` ON `waitlist_entries` (`email`);